apiVersion: v1
kind: Template
labels:
  template: python-builder
metadata:
  annotations:
    description: Python s2i build components
    tags: python, s2i
  name: "${APPLICATION_NAME}"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Python s2i Source BuildConfig
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: "${APPLICATION_SOURCE_REPOSITORY_REF}"
        uri: "${APPLICATION_SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: The name of the application
  name: APPLICATION_NAME
  required: true
  value: hello-world
- description: Python application git branch/tag reference
  name: APPLICATION_SOURCE_REPOSITORY_REF
  value: master
- description: Python application git source URL
  name: APPLICATION_SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/cricci82/hello-world-instrumented