apiVersion: v1
kind: Template
labels:
  template: imagestreams
metadata:
  name: "${IS_NAME}"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: "${IS_NAME}"
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: "${IS_NAME}:${IS_TAG}"
      importPolicy: {}
      name: "${IS_TAG}"
parameters:
- description: Name of imagestream
  name: IS_NAME
  required: true
- description: Name of imagestream tag
  name: IS_TAG
  required: true
  value: latest