apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-production
  labels:
    version: v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        env: production
    spec:
      containers:
      - name: hello-world 
        image: 172.30.1.1:5000/dj18/hello-world:latest
        #image: quay.io/chris_ricci/hello-world-instrumented:v1
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
        - name: metrics
          containerPort: 8000
